<?php

const HIGHLIGHT_LEVELS = [
    'primary',
    'secondary',
    'success',
    'danger',
    'warning',
    'gray'
];

const HIGHLIGHT_LEVEL_PRIMARY = HIGHLIGHT_LEVELS[0];
const HIGHLIGHT_LEVEL_SECONDARY = HIGHLIGHT_LEVELS[1];
const HIGHLIGHT_LEVEL_SUCCESS = HIGHLIGHT_LEVELS[2];
const HIGHLIGHT_LEVEL_DANGER = HIGHLIGHT_LEVELS[3];
const HIGHLIGHT_LEVEL_WARNING = HIGHLIGHT_LEVELS[4];
const HIGHLIGHT_LEVEL_GRAY = HIGHLIGHT_LEVELS[5];

const INGREDIENT_BASE_UNIT = [
    'g',
    'ml',
    'piece',
    'stalk',
    'bottle',
    'pack',
];

const INGREDIENT_BASE_UNIT_GRAM = INGREDIENT_BASE_UNIT[0];
const INGREDIENT_BASE_UNIT_MILLILITER = INGREDIENT_BASE_UNIT[1];
const INGREDIENT_BASE_UNIT_PIECE = INGREDIENT_BASE_UNIT[2];
const INGREDIENT_BASE_UNIT_STALK = INGREDIENT_BASE_UNIT[3];
const INGREDIENT_BASE_UNIT_BOTTLE = INGREDIENT_BASE_UNIT[4];
const INGREDIENT_BASE_UNIT_PACK = INGREDIENT_BASE_UNIT[5];

const INGREDIENT_BASE_UNIT_LABELS = [
    INGREDIENT_BASE_UNIT_GRAM => 'g',
    INGREDIENT_BASE_UNIT_MILLILITER => 'ml',
    INGREDIENT_BASE_UNIT_PIECE => 'miếng',
    INGREDIENT_BASE_UNIT_STALK => 'cọng',
    INGREDIENT_BASE_UNIT_BOTTLE => 'chai',
    INGREDIENT_BASE_UNIT_PACK => 'gói',
];

const PACKAGE_STATUS = [
    'open',
    'used_up',
    'expired',
    'discarded'
];

const PACKAGE_STATUS_OPEN = PACKAGE_STATUS[0];
const PACKAGE_STATUS_USED_UP = PACKAGE_STATUS[1];
const PACKAGE_STATUS_EXPIRED = PACKAGE_STATUS[2];
const PACKAGE_STATUS_DISCARDED = PACKAGE_STATUS[3];

const RECORD_STATUS = [
    'active',
    'inactive',
];

const RECORD_STATUS_DEFAULT = 'active';
const RECORD_STATUS_ACTIVE = RECORD_STATUS[0];
const RECORD_STATUS_INACTIVE = RECORD_STATUS[1];

const RECORD_STATUS_LABELS = [
    RECORD_STATUS_ACTIVE => 'Hoạt động',
    RECORD_STATUS_INACTIVE => 'Ngừng hoạt động',
];

const RECORD_STATUS_COLORS = [
    RECORD_STATUS_ACTIVE => HIGHLIGHT_LEVEL_SUCCESS,
    RECORD_STATUS_INACTIVE => HIGHLIGHT_LEVEL_DANGER,
];


const INVENTORY_ACTION_TYPES = [
    'receive',
    'open',
    'consume',
    'discard',
    'expire',
    'rollback'
];

const INVENTORY_ACTION_TYPE_RECEIVE = INVENTORY_ACTION_TYPES[0];
const INVENTORY_ACTION_TYPE_OPEN = INVENTORY_ACTION_TYPES[1];
const INVENTORY_ACTION_TYPE_CONSUME = INVENTORY_ACTION_TYPES[2];
const INVENTORY_ACTION_TYPE_DISCARD = INVENTORY_ACTION_TYPES[3];
const INVENTORY_ACTION_TYPE_EXPIRE = INVENTORY_ACTION_TYPES[4];
const INVENTORY_ACTION_TYPE_ROLLBACK = INVENTORY_ACTION_TYPES[5];

const ORDER_STATUSES = [
    'draft',
    'confirmed',
    'paid',
    'completed',
    'cancelled'
];

const ORDER_STATUS_DEFAULT = ORDER_STATUSES[0];
const ORDER_STATUS_CONFIRMED = ORDER_STATUSES[1];
const ORDER_STATUS_PAID = ORDER_STATUSES[2];
const ORDER_STATUS_COMPLETED = ORDER_STATUSES[3];
const ORDER_STATUS_CANCELLED = ORDER_STATUSES[4];

const ORDER_STATUS_COLORS = [
    ORDER_STATUS_DEFAULT => HIGHLIGHT_LEVEL_SECONDARY,
    ORDER_STATUS_CONFIRMED => HIGHLIGHT_LEVEL_PRIMARY,
    ORDER_STATUS_PAID => HIGHLIGHT_LEVEL_WARNING,
    ORDER_STATUS_COMPLETED => HIGHLIGHT_LEVEL_SUCCESS,
    ORDER_STATUS_CANCELLED => HIGHLIGHT_LEVEL_DANGER,
];

const ORDER_STATUS_LABELS = [
    ORDER_STATUS_DEFAULT => "Hóa đơn nháp",
    ORDER_STATUS_CONFIRMED => "Đã xác nhận",
    ORDER_STATUS_PAID => "Đã thanh toán",
    ORDER_STATUS_COMPLETED => "Hoàn tất",
    ORDER_STATUS_CANCELLED => "Đã hủy",
];

const ORDER_FEASIBILITY_OK = 'ok';
const ORDER_FEASIBILITY_IMPOSSIBLE = 'impossible';
const ORDER_FEASIBILITY_REQUIRE_OPEN = 'require_open';
const ORDER_FEASIBILITY_RISKY = 'risky';

const DOMAIN_EXCEPTION_NO_LOT_FOUND = 'NO_INVENTORY_LOT_FOUND';
const DOMAIN_EXCEPTION_ORDER_NOT_PAID = 'ORDER_NOT_PAID';
const DOMAIN_EXCEPTION_INVENTORY_ALREADY_CONSUMED = 'INVENTORY_ALREADY_CONSUMED';
const DOMAIN_EXCEPTION_INVENTORY_INSUFFICIENT = 'INVENTORY_INSUFFICIENT';
const DOMAIN_EXCEPTION_ORDER_NOT_CONSUMED = 'ORDER_NOT_CONSUMED';
const DOMAIN_EXCEPTION_ORDER_NOT_ROLLBACKABLE = 'ORDER_NOT_ROLLBACKABLE';
const DOMAIN_EXCEPTION_NO_BATCH_FOUND = 'NO_INVENTORY_BATCH_FOUND';

const EMPLOYEE_ROLES = [
    'manager',
    'bartender',
    'waiter',
    'cleanner'
];

const EMPLOYEE_ROLE_MANAGER = EMPLOYEE_ROLES[0];
const EMPLOYEE_ROLE_BARTENDER = EMPLOYEE_ROLES[1];
const EMPLOYEE_ROLE_WAITER = EMPLOYEE_ROLES[2];
const EMPLOYEE_ROLE_CLEANNER = EMPLOYEE_ROLES[3];

const EMPLOYEE_ROLE_LABELS = [
    EMPLOYEE_ROLE_MANAGER => 'Quản lý',
    EMPLOYEE_ROLE_BARTENDER => 'Pha chế',
    EMPLOYEE_ROLE_WAITER => 'Phục vụ',
    EMPLOYEE_ROLE_CLEANNER => 'Dọn dẹp',
];

const EMPLOYEE_ROLE_COLORS = [
    EMPLOYEE_ROLE_MANAGER => HIGHLIGHT_LEVEL_PRIMARY,
    EMPLOYEE_ROLE_BARTENDER => HIGHLIGHT_LEVEL_SUCCESS,
    EMPLOYEE_ROLE_WAITER => HIGHLIGHT_LEVEL_WARNING,
    EMPLOYEE_ROLE_CLEANNER => HIGHLIGHT_LEVEL_DANGER,
];

const SCHEDULE_STATUSS = [
    'scheduled',
    'in_progress',
    'completed',
    'cancelled'
];

const SCHEDULE_STATUS_SCHEDULED = SCHEDULE_STATUSS[0];
const SCHEDULE_STATUS_IN_PROGRESS = SCHEDULE_STATUSS[1];
const SCHEDULE_STATUS_COMPLETED = SCHEDULE_STATUSS[2];
const SCHEDULE_STATUS_CANCELLED = SCHEDULE_STATUSS[3];

const SCHEDULE_STATUS_LABELS = [
    SCHEDULE_STATUS_SCHEDULED => 'Đã lên lịch',
    SCHEDULE_STATUS_IN_PROGRESS => 'Đang tiến hành',
    SCHEDULE_STATUS_COMPLETED => 'Hoàn tất',
    SCHEDULE_STATUS_CANCELLED => 'Đã hủy',
];

const SCHEDULE_STATUS_COLORS = [
    SCHEDULE_STATUS_SCHEDULED => HIGHLIGHT_LEVEL_SECONDARY,
    SCHEDULE_STATUS_IN_PROGRESS => HIGHLIGHT_LEVEL_PRIMARY,
    SCHEDULE_STATUS_COMPLETED => HIGHLIGHT_LEVEL_SUCCESS,
    SCHEDULE_STATUS_CANCELLED => HIGHLIGHT_LEVEL_DANGER,
];

const PAYROLL_STATUSES = [
    'pending',
    'paid',
];

const PAYROLL_STATUS_PENDING = PAYROLL_STATUSES[0];
const PAYROLL_STATUS_PAID = PAYROLL_STATUSES[1];

const PAYROLL_STATUS_LABELS = [
    PAYROLL_STATUS_PENDING => 'Chưa trả',
    PAYROLL_STATUS_PAID => 'Đã trả',
];

const PAYROLL_STATUS_COLORS = [
    PAYROLL_STATUS_PENDING => HIGHLIGHT_LEVEL_WARNING,
    PAYROLL_STATUS_PAID => HIGHLIGHT_LEVEL_SUCCESS,
];
