<?php

const HIGHLIGHT_LEVELS = [
    'primary',
    'secondary',
    'success',
    'danger',
    'warning',
    'gray'
];

const HIGHLIGHT_LEVEL_PRIMARY = HIGHLIGHT_LEVELS[0];
const HIGHLIGHT_LEVEL_SECONDARY = HIGHLIGHT_LEVELS[1];
const HIGHLIGHT_LEVEL_SUCCESS = HIGHLIGHT_LEVELS[2];
const HIGHLIGHT_LEVEL_DANGER = HIGHLIGHT_LEVELS[3];
const HIGHLIGHT_LEVEL_WARNING = HIGHLIGHT_LEVELS[4];
const HIGHLIGHT_LEVEL_GRAY = HIGHLIGHT_LEVELS[5];

const INGREDIENT_BASE_UNIT = [
    'g',
    'ml',
    'piece',
    'stalk',
    'bottle',
    'pack',
];

const INGREDIENT_BASE_UNIT_GRAM = INGREDIENT_BASE_UNIT[0];
const INGREDIENT_BASE_UNIT_MILLILITER = INGREDIENT_BASE_UNIT[1];
const INGREDIENT_BASE_UNIT_PIECE = INGREDIENT_BASE_UNIT[2];
const INGREDIENT_BASE_UNIT_STALK = INGREDIENT_BASE_UNIT[3];
const INGREDIENT_BASE_UNIT_BOTTLE = INGREDIENT_BASE_UNIT[4];
const INGREDIENT_BASE_UNIT_PACK = INGREDIENT_BASE_UNIT[5];

const INGREDIENT_BASE_UNIT_LABELS = [
    INGREDIENT_BASE_UNIT_GRAM => 'g',
    INGREDIENT_BASE_UNIT_MILLILITER => 'ml',
    INGREDIENT_BASE_UNIT_PIECE => 'miếng',
    INGREDIENT_BASE_UNIT_STALK => 'cọng',
    INGREDIENT_BASE_UNIT_BOTTLE => 'chai',
    INGREDIENT_BASE_UNIT_PACK => 'gói',
];

const PACKAGE_STATUS = [
    'open',
    'used_up',
    'expired',
    'discarded'
];

const PACKAGE_STATUS_OPEN = PACKAGE_STATUS[0];
const PACKAGE_STATUS_USED_UP = PACKAGE_STATUS[1];
const PACKAGE_STATUS_EXPIRED = PACKAGE_STATUS[2];
const PACKAGE_STATUS_DISCARDED = PACKAGE_STATUS[3];

const RECORD_STATUS = [
    'active',
    'inactive',
];

const RECORD_STATUS_DEFAULT = 'active';
const RECORD_STATUS_ACTIVE = RECORD_STATUS[0];
const RECORD_STATUS_INACTIVE = RECORD_STATUS[1];

const RECORD_STATUS_LABELS = [
    RECORD_STATUS_ACTIVE => 'Hoạt động',
    RECORD_STATUS_INACTIVE => 'Ngừng hoạt động',
];

const RECORD_STATUS_COLORS = [
    RECORD_STATUS_ACTIVE => HIGHLIGHT_LEVEL_SUCCESS,
    RECORD_STATUS_INACTIVE => HIGHLIGHT_LEVEL_DANGER,
];


const INVENTORY_ACTION_TYPES = [
    'receive',
    'open',
    'consume',
    'discard',
    'expire',
    'rollback'
];

const INVENTORY_ACTION_TYPE_RECEIVE = INVENTORY_ACTION_TYPES[0];
const INVENTORY_ACTION_TYPE_OPEN = INVENTORY_ACTION_TYPES[1];
const INVENTORY_ACTION_TYPE_CONSUME = INVENTORY_ACTION_TYPES[2];
const INVENTORY_ACTION_TYPE_DISCARD = INVENTORY_ACTION_TYPES[3];
const INVENTORY_ACTION_TYPE_EXPIRE = INVENTORY_ACTION_TYPES[4];
const INVENTORY_ACTION_TYPE_ROLLBACK = INVENTORY_ACTION_TYPES[5];

const ORDER_STATUSES = [
    'draft',
    'confirmed',
    'paid',
    'completed',
    'cancelled'
];

const ORDER_STATUS_DEFAULT = ORDER_STATUSES[0];
const ORDER_STATUS_CONFIRMED = ORDER_STATUSES[1];
const ORDER_STATUS_PAID = ORDER_STATUSES[2];
const ORDER_STATUS_COMPLETED = ORDER_STATUSES[3];
const ORDER_STATUS_CANCELLED = ORDER_STATUSES[4];

const ORDER_STATUS_COLORS = [
    ORDER_STATUS_DEFAULT => HIGHLIGHT_LEVEL_SECONDARY,
    ORDER_STATUS_CONFIRMED => HIGHLIGHT_LEVEL_PRIMARY,
    ORDER_STATUS_PAID => HIGHLIGHT_LEVEL_WARNING,
    ORDER_STATUS_COMPLETED => HIGHLIGHT_LEVEL_SUCCESS,
    ORDER_STATUS_CANCELLED => HIGHLIGHT_LEVEL_DANGER,
];

const ORDER_STATUS_LABELS = [
    ORDER_STATUS_DEFAULT => "Hóa đơn nháp",
    ORDER_STATUS_CONFIRMED => "Đã xác nhận",
    ORDER_STATUS_PAID => "Đã thanh toán",
    ORDER_STATUS_COMPLETED => "Hoàn tất",
    ORDER_STATUS_CANCELLED => "Đã hủy",
];

const ORDER_FEASIBILITY_OK = 'ok';
const ORDER_FEASIBILITY_IMPOSSIBLE = 'impossible';
const ORDER_FEASIBILITY_REQUIRE_OPEN = 'require_open';
const ORDER_FEASIBILITY_RISKY = 'risky';

const DOMAIN_EXCEPTION_NO_LOT_FOUND = 'NO_INVENTORY_LOT_FOUND';
const DOMAIN_EXCEPTION_ORDER_NOT_PAID = 'ORDER_NOT_PAID';
const DOMAIN_EXCEPTION_INVENTORY_ALREADY_CONSUMED = 'INVENTORY_ALREADY_CONSUMED';
const DOMAIN_EXCEPTION_INVENTORY_INSUFFICIENT = 'INVENTORY_INSUFFICIENT';
const DOMAIN_EXCEPTION_ORDER_NOT_CONSUMED = 'ORDER_NOT_CONSUMED';
const DOMAIN_EXCEPTION_ORDER_NOT_ROLLBACKABLE = 'ORDER_NOT_ROLLBACKABLE';
const DOMAIN_EXCEPTION_NO_BATCH_FOUND = 'NO_INVENTORY_BATCH_FOUND';
